package com.sora.common.http;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RespState {

    SUCCESS(200, "SUCCESS"),
    FAILURE(300, "FAILURE"),
    ILLEGAL(400, "ILLEGAL"),

    NOT_AUTHORIZED(401, "NOT AUTHORIZED"),
    BAD_CREDENTIAL(402, "BAD CREDENTIAL"),
    ACCOUNT_EXPIRE(402, "ACCOUNT EXPIRE"),
    ACCOUNT_LOCKED(402, "ACCOUNT LOCKED"),
    TOKEN_UNKNOWN(401, "TOKEN UNKNOWN"),
    TOKEN_INVALID(401, "TOKEN INVALID"),
    TOKEN_EXPIRED(401, "TOKEN EXPIRED"),
    ACCESS_DENIED(403, "ACCESS DENIED"),

    DATA_NOTFOUND(501, "DATA NOTFOUND"),
    REPEAT_RECORD(502, "REPEAT RECORD"),
    USER_NOTFOUND(503, "USER NOTFOUND"),
    ACCOUNT_EXIST(504, "ACCOUNT EXIST"),
    MOBILE_EXISTS(505, "MOBILE EXISTS"),
    PHONE_ILLEGAL(505, "PHONE ILLEGAL"),
    RELATE_EXISTS(506, "RELATE EXISTS"),
    EQUALS_EXISTS(507, "EQUALS EXISTS"),
    ACTIVE_ENABLE(508, "ACTIVE ENABLE"),
    FORBID_DELETE(509, "FORBID DELETE"),

    CAPTCHA_EMPTIES(601, "CAPTCHA EMPTIES"),
    CAPTCHA_EXPIRED(602, "CAPTCHA EXPIRED"),
    CAPTCHA_FAILURE(603, "CAPTCHA FAILURE"),

    QR_CODE_EXPIRED(606, "QR CODE EXPIRED"),
    QR_CODE_FAILURE(605, "QR CODE FAILURE"),

    INSERT_FAILURE(701, "INSERT FAILURE"),
    DELETE_FAILURE(702, "DELETE FAILURE"),
    UPDATE_FAILURE(703, "UPDATE FAILURE"),
    SELECT_FAILURE(704, "SELECT FAILURE"),

    EXPENSE_FINISH(801, "EXPENSE FINISH"),
    PAYMENT_FINISH(802, "PAYMENT FINISH"),
    EXPENSE_UNPAID(802, "EXPENSE UNPAID");;

    private Integer status;

    private String message;


}
